coverage:
  status:
    project:
      default:
        target: 100%
        threshold: 1%

comment:
  layout: "condensed_header, diff, flags, components"

component_management:
  individual_components:
    - component_id: api #identifier that shouldn't be changed
      name: api #display name; change it freely
      paths:
        - api
